# Generated by Django 3.1.2 on 2020-11-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201119_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='bit_depth_rating',
            field=models.CharField(blank=True,
                                   default='Unknown',
                                   max_length=64,
                                   null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='bit_rate_rating',
            field=models.CharField(blank=True,
                                   default='Unknown',
                                   max_length=64,
                                   null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='frame_rate_rating',
            field=models.CharField(blank=True,
                                   default='Unknown',
                                   max_length=64,
                                   null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='resolution_rating',
            field=models.CharField(blank=True,
                                   default='Unknown',
                                   max_length=64,
                                   null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='sample_rate_rating',
            field=models.CharField(blank=True,
                                   default='Unknown',
                                   max_length=64,
                                   null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='shutter_speed_rating',
            field=models.CharField(blank=True,
                                   default='Unknown',
                                   max_length=64,
                                   null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_length_rating',
            field=models.CharField(blank=True,
                                   default='Unknown',
                                   max_length=64,
                                   null=True),
        ),
    ]
