# Generated by Django 3.1.3 on 2020-11-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201119_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_length',
            field=models.CharField(blank=True, default='Unknown', max_length=64, null=True),
        ),
    ]
