# Generated by Django 3.1.3 on 2020-11-27 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201124_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='shutter_speed',
        ),
        migrations.RemoveField(
            model_name='video',
            name='shutter_speed_rating',
        ),
        migrations.RemoveField(
            model_name='video',
            name='shutter_speed_recommendation',
        ),
    ]
