# Generated by Django 3.1.5 on 2021-01-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201127_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='bit_depth_recommended',
            field=models.CharField(blank=True,
                                   default='Unknown',
                                   max_length=64,
                                   null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='bit_rate_recommended',
            field=models.CharField(blank=True,
                                   default='Unknown',
                                   max_length=64,
                                   null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='frame_rate_recommended',
            field=models.CharField(blank=True,
                                   default='Unknown',
                                   max_length=64,
                                   null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='resolution_recommended',
            field=models.CharField(blank=True,
                                   default='Unknown',
                                   max_length=64,
                                   null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='sample_rate_recommended',
            field=models.CharField(blank=True,
                                   default='Unknown',
                                   max_length=64,
                                   null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_length_recommended',
            field=models.CharField(blank=True,
                                   default='Unknown',
                                   max_length=64,
                                   null=True),
        ),
    ]
